web:
  build: .
  links:
   - db
  ports:
   - "3333:3333"
   - "35729:35729"
  volumes:
   - "./app:/src/app"
  # all env items should be in .env
  env_file: .env

db:
  #https://hub.docker.com/_/mongo/
  # @TODO: we want an alpine mongodb...
  image: mongo:3.3
  ports:
   - "27017:27017"
