---

builds:
  docker_image_name: FreeLunchCI/example-mean

services:
  db:
  image: mongo:3.3
  ports:
   - "27017:27017"
web:
  build: .
  command: python -u run.py
  ports:
    - "3333:3333"
    - "35729:35729"
links:
  - db
volumes:
  - "./app:/src/app"

outputs:

  - type: ecr
    image: FreeLunchCI/example-mean
    registry: 703587889398.dkr.ecr.us-east-1.amazonaws.com
    repository: example-mean

#  - type: kube
#    server: https://50.16.94.175
#    user: aws_kubernetes
#    #token: this value is stored/retrieved from the "secure store"
#    #client_certificate: this value is stored/retrieved from the "secure store"
#
#    kube_selector: app=example-mean
#    kube_deploy_registry: 703587889398.dkr.ecr.us-east-1.amazonaws.com   # this should match the registry you deploy your image to (e.g. ecr.registry)
#    kube_deploy_repository: example-mean   # this should match the repository within the registry that you deploy your image to (e.g. ecr.repository)
#    kube_rc_path: k8s/example-mean-rc.yml
#    kube_dir: k8s
