apiVersion: v1
kind: Service
metadata:
  name: example-mean-todo-elb
  labels:
    app: example-mean-todo
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3333
    targetPort: 3333
  selector:
    app: example-mean-todo
