apiVersion: v1
kind: ReplicationController
metadata:
  name: example-mean-todo
  labels:
    app: example-mean-todo
spec:
  replicas: 1
  selector:
    app: example-mean-todo
    version: green
  template:
    metadata:
      labels:
        app: example-mean-todo
        version: green
    spec:
      containers:
      - name: example-mean-todo
        imagePullPolicy: Always
        image: 703587889398.dkr.ecr.us-east-1.amazonaws.com/example-mean-todo:latest
        ports:
        - name: appport
          containerPort: 27017
